spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devstronomy
    username: root
    password: root

logging.level:
  root: INFO
  com.devstronomy: INFO
  org.springframework: INFO
  com.fasterxml.jackson: INFO
  org.hibernate.SQL: DEBUG
